# Generated by Django 5.0.1 on 2024-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_carttable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='sku',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttable',
            name='category',
            field=models.IntegerField(choices=[(1, 'Sneaker'), (2, 'Juti'), (3, 'Tux shoes'), (4, 'Boots'), (5, 'Sandals')]),
        ),
    ]
