# Generated by Django 5.0.1 on 2024-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producttable_sku_alter_producttable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
