# Generated by Django 5.0.1 on 2024-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_producttable_size_alter_producttable_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='category',
            field=models.IntegerField(choices=[(1, 'Sneaker/Shoes'), (2, 'Juti'), (3, 'Bags'), (4, 'Boots/Sandals'), (5, 'Belts')]),
        ),
    ]
